# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 6, 23, 17, 35, 59, 278000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
